DIM __NUMBER_VAR__ AS INTEGER
PRINT "ENTER A NUMBER: ";

INPUT __NUMBER_VAR__

IF (__NUMBER_VAR__ < 0) THEN GOTO __NEGATIVE
IF (__NUMBER_VAR__ > 0) THEN GOTO __POSITIVE

PRINT "__NUMBER_VAR__ = 0"
GOTO __DONE

__NEGATIVE:
    PRINT "__NUMBER_VAR__ < 0"
    GOTO __DONE

__POSITIVE:
    PRINT "__NUMBER_VAR__ > 0"

__DONE: