DIM __ARRAY_VAR__() AS INTEGER
DIM __SIZE_VAR__ AS INTEGER
DIM __INDEX__ AS INTEGER

PRINT "SET THE SIZE OF ARRAY: ";
INPUT __SIZE_VAR__

__SIZE_VAR__ = __SIZE_VAR__ - 1 ' SINCE, ARRAYS STARTS FROM 0
' NOT LIKE C, THE SIZE MUST BE CERTAIN. ONE BYTE IS REALLY IMPORTANT ON
' CERTAIN SITUATIONS
REDIM __ARRAY_VAR__(__SIZE_VAR__) ' KIND OF MALLOC()

FOR __INDEX__ = 0 TO __SIZE_VAR__
	__ARRAY_VAR__(__INDEX__) = __INDEX__ + 1
NEXT __INDEX__

PRINT "Array elements: "

FOR __INDEX__ = 0 TO __SIZE_VAR__
	PRINT "__ARRAY_VAR__(" & __INDEX__ & ") = " & __ARRAY_VAR__(__INDEX__)
NEXT __INDEX__
