DIM __ARRAY_VAR__(5) AS INTEGER
DIM INDEX AS INTEGER

__ARRAY_VAR__(0) = 10
__ARRAY_VAR__(1) = 20
__ARRAY_VAR__(2) = 30
__ARRAY_VAR__(3) = 40
__ARRAY_VAR__(4) = 50

FOR INDEX = 0 TO 4
	PRINT "__ARRAY_VAR__(" & INDEX & ") = "; __ARRAY_VAR__(INDEX)
NEXT INDEX
