TYPE PERSON_TYPE
	__NAME__ AS STRING
	__AGE__ AS INTEGER
	DECLARE CONSTRUCTOR (BYVAL VAR_NAME AS STRING, BYVAL VAR_AGE AS INTEGER)
END TYPE

CONSTRUCTOR PERSON_TYPE (BYVAL VAR_NAME AS STRING, BYVAL VAR_AGE AS INTEGER)
	this.__NAME__ = VAR_NAME
	this.__AGE__ = VAR_AGE
END CONSTRUCTOR

DIM __PERSON__ AS PERSON_TYPE = PERSON_TYPE("TEOMAN", 25)

PRINT "NAME: " & __PERSON__.__NAME__
PRINT "AGE: " & __PERSON__.__AGE__
