TYPE PERSON_TYPE
	__NAME__ AS STRING
	__AGE__ AS INTEGER
END TYPE

DIM __PERSON__ AS PERSON_TYPE

__PERSON__.__NAME__ = "TEOMAN DENIZ"
__PERSON__.__AGE__ = 30

PRINT "NAME: " & __PERSON__.__NAME__
PRINT "AGE: " & __PERSON__.__AGE__
