DIM __STRING_1__ AS STRING
DIM __STRING_2__ AS STRING

PRINT "STRING_1: "
INPUT __STRING_1__

PRINT "STRING_2: "
INPUT __STRING_2__

IF (__STRING_1__ = __STRING_2__) THEN
	PRINT "STRINGS ARE SAME!"
ELSE
	PRINT "STRINGS ARE DIFFERENT!"
END IF
