DIM __STRING_VAR__ AS STRING
DIM __POSITION__ AS INTEGER

__STRING_VAR__ = "TEO MAN DEN IZ"

__POSITION__ = INSTR(__STRING_VAR__, "MAN")

IF (__POSITION__ > 0) THEN
	PRINT "'MAN' FOUND AT: " & __POSITION__
ELSE
	PRINT "'MAN' NOT FOUND IN STRING"
END IF
