DIM __STRING_VAR__ AS STRING

PRINT "WRITE A STRING"
INPUT __STRING_VAR__

PRINT "UPPERCASE VERSION OF YOUR STRING: " & UCASE(__STRING_VAR__)
PRINT "LOWERCASE VERSION OF YOUR STRING: " & LCASE(__STRING_VAR__)
