DIM __FILE_VAR__ AS INTEGER
DIM __LINE_VAR__ AS STRING

__FILE_VAR__ = FREEFILE

OPEN "PRINT.bas" FOR INPUT AS #__FILE_VAR__
WHILE NOT EOF(__FILE_VAR__)
	LINE INPUT #__FILE_VAR__, __LINE_VAR__
	PRINT __LINE_VAR__
WEND

CLOSE #__FILE_VAR__
