DIM __FILE_VAR__ AS INTEGER

__FILE_VAR__ = FREEFILE

OPEN "TEST.TXT" FOR OUTPUT AS #__FILE_VAR__

PRINT #__FILE_VAR__, "TEST"
PRINT #__FILE_VAR__, "TEST 2" & 42

CLOSE #__FILE_VAR__

PRINT "DATA WRITTEN IN TEST.TXT"
